'use strict';

const projectService = require('./projectService');
const projectFileService = require('./projectFileService');
const projectFileRepository = require('../repositories/projectFileRepository');
const dependencyRepository = require('../repositories/dependencyRepository');
const relationshipRepository = require('../repositories/relationshipRepository');
const apiEndpointRepository = require('../repositories/apiEndpointRepository');
const databaseEntityRepository = require('../repositories/databaseEntityRepository');
const issueRepository = require('../repositories/issueRepository');
const securityFindingRepository = require('../repositories/securityFindingRepository');
const contextBuilder = require('../ai/context');
const aiProvider = require('../ai/provider');
const config = require('../config/env');
const { logger } = require('../utils/logger');

// Impact Analysis (docs/PROJECT_SPEC.md section 6, docs/API_CONTRACT.md section 22.1,
// docs/ARCHITECTURE.md section 10).
//
// Identifies affected components using stored analyzer relationships and dependencies
// ONLY. No graph relationships are invented or generated by AI. AI can optionally be
// used to explain the generated impact narrative.

function extractArchitectureArea(filePath) {
  if (!filePath) return 'root';
  const posixPath = filePath.replace(/\\/g, '/');
  const parts = posixPath.split('/');
  if (parts.length === 1) return 'root';
  // If top-level is backend/frontend/analyzer, take first 2 parts (e.g. backend/controllers)
  if (['backend', 'frontend', 'analyzer', 'src'].includes(parts[0]) && parts.length > 2) {
    return `${parts[0]}/${parts[1]}`;
  }
  return parts[0];
}

async function getFileImpact(userId, projectId, fileId, options = {}) {
  const shouldExplain = Boolean(options.explain);

  // 1. Verify project ownership (docs/API_CONTRACT.md section 26)
  const project = await projectService.getOwnedProject(userId, projectId);

  // 2. Verify target file exists and belongs to project
  const targetFile = await projectFileService.requireProjectFile(project.id, fileId);
  const anchorId = Number(targetFile.id);

  // 3. Retrieve all code relationships & project files for graph traversal
  const [allEdges, projectDependencies, allFiles] = await Promise.all([
    relationshipRepository.findByProjectId(project.id),
    dependencyRepository.findByProjectId(project.id),
    projectFileRepository.findByProjectId(project.id),
  ]);

  const fileMap = new Map(allFiles.map((f) => [Number(f.id), f]));

  // Build graph adjacency maps
  const forwardMap = new Map(); // source_file_id -> outgoing edges (dependencies)
  const reverseMap = new Map(); // target_file_id -> incoming edges (dependents)

  for (const edge of allEdges) {
    const sourceId = Number(edge.source_file_id);
    if (!forwardMap.has(sourceId)) forwardMap.set(sourceId, []);
    forwardMap.get(sourceId).push(edge);

    if (edge.target_file_id !== null && edge.target_file_id !== undefined) {
      const targetId = Number(edge.target_file_id);
      if (!reverseMap.has(targetId)) reverseMap.set(targetId, []);
      reverseMap.get(targetId).push(edge);
    }
  }

  // Direct dependencies (files imported by target file)
  const dependencyEdges = forwardMap.get(anchorId) || [];
  const dependsOn = dependencyEdges.map((edge) => {
    const targetId = edge.target_file_id !== null ? Number(edge.target_file_id) : null;
    const targetFileRow = targetId ? fileMap.get(targetId) : null;
    return {
      fileId: targetId,
      path: targetFileRow ? targetFileRow.path : (edge.target_path || null),
      symbol: edge.symbol_name || null,
      relationshipType: edge.relationship_type || 'imports',
    };
  });

  const directDependencyIds = [...new Set(
    dependsOn.map((d) => d.fileId).filter((id) => id !== null && id !== anchorId),
  )];

  // Direct dependents (files importing target file)
  const dependentEdges = reverseMap.get(anchorId) || [];
  const usedBy = dependentEdges.map((edge) => {
    const sourceId = Number(edge.source_file_id);
    const sourceFileRow = fileMap.get(sourceId);
    return {
      fileId: sourceId,
      path: sourceFileRow ? sourceFileRow.path : (edge.source_path || null),
      symbol: edge.symbol_name || null,
      relationshipType: edge.relationship_type || 'imports',
    };
  });

  const directDependentIds = [...new Set(
    usedBy.map((d) => d.fileId).filter((id) => id !== null && id !== anchorId),
  )];

  // Transitive dependents (second hop: files importing direct dependents)
  const secondHopEdges = [];
  const secondHopIds = new Set();
  for (const dependentId of directDependentIds) {
    const edges = reverseMap.get(dependentId) || [];
    for (const edge of edges) {
      const sourceId = Number(edge.source_file_id);
      if (sourceId !== anchorId && !directDependentIds.includes(sourceId)) {
        if (!secondHopIds.has(sourceId)) {
          secondHopIds.add(sourceId);
          secondHopEdges.push(edge);
        }
      }
    }
  }

  const transitiveDependents = [...secondHopIds].map((sourceId) => {
    const fileRow = fileMap.get(sourceId);
    return {
      fileId: sourceId,
      path: fileRow ? fileRow.path : null,
    };
  });

  // Unique affected file IDs (anchor + direct dependencies + direct dependents + transitive)
  const affectedFileIds = [
    anchorId,
    ...directDependencyIds,
    ...directDependentIds,
    ...secondHopIds,
  ];

  // Fetch detailed entities for affected file set
  const [affectedFiles, affectedApis, affectedDatabases, affectedIssues, affectedFindings] = await Promise.all([
    projectFileRepository.findByIds(project.id, affectedFileIds),
    apiEndpointRepository.findByFileIds(project.id, affectedFileIds),
    databaseEntityRepository.findByFileIds(project.id, affectedFileIds),
    issueRepository.findByFileIds(project.id, affectedFileIds),
    securityFindingRepository.findByFileIds(project.id, affectedFileIds),
  ]);

  // Determine affected architecture areas
  const areaSet = new Set();
  for (const fileRow of affectedFiles) {
    areaSet.add(extractArchitectureArea(fileRow.path));
  }
  const architectureAreas = [...areaSet].sort();

  // Related package dependencies (manifest dependencies declared in source or affected files)
  const relatedPackageDependencies = projectDependencies.filter((dep) => {
    if (!dep.source_file_id) return false;
    return affectedFileIds.includes(Number(dep.source_file_id));
  }).map((dep) => ({
    id: Number(dep.id),
    name: dep.name,
    version: dep.version,
    type: dep.dependency_type,
    packageManager: dep.package_manager,
  }));

  // Build clean response structure
  const impactData = {
    fileId: anchorId,
    filePath: targetFile.path,
    dependsOn,
    usedBy,
    transitiveDependents,
    relatedFiles: affectedFiles.map((f) => ({
      fileId: Number(f.id),
      path: f.path,
      name: f.name,
      language: f.language,
      healthStatus: f.health_status,
      healthScore: Number(f.health_score) || 0,
    })),
    affectedApis: affectedApis.map((api) => ({
      id: Number(api.id),
      method: api.method,
      route: api.route,
      controllerName: api.controller_name,
      filePath: api.file_path,
    })),
    affectedDatabases: affectedDatabases.map((db) => ({
      id: Number(db.id),
      name: db.name,
      entityType: db.entity_type,
      databaseName: db.database_name,
      filePath: db.file_path,
    })),
    affectedIssues: affectedIssues.map((issue) => ({
      id: Number(issue.id),
      title: issue.title,
      severity: issue.severity,
      issueType: issue.issue_type,
      filePath: issue.file_path,
    })),
    affectedSecurityFindings: affectedFindings.map((finding) => ({
      id: Number(finding.id),
      title: finding.title,
      severity: finding.severity,
      category: finding.category,
      filePath: finding.file_path,
    })),
    relatedPackageDependencies,
    architectureAreas,
    summary: {
      directDependenciesCount: dependsOn.length,
      directDependentsCount: usedBy.length,
      transitiveDependentsCount: transitiveDependents.length,
      totalAffectedFilesCount: affectedFiles.length,
      affectedApisCount: affectedApis.length,
      affectedDatabasesCount: affectedDatabases.length,
      affectedIssuesCount: affectedIssues.length,
      affectedSecurityCount: affectedFindings.length,
    },
    explanation: null,
  };

  // Optional AI narrative explanation
  if (shouldExplain) {
    try {
      const impactContext = await contextBuilder.buildImpactContext(project.id, targetFile.id);
      const systemPrompt = `You are an expert software architect analyzing code change impacts.
Explain the technical impact of modifying the target file based ONLY on the provided factual context.
Identify key risks, affected APIs, dependent modules, and what needs testing.
Do not invent any file relationships or dependencies not present in the context.`;

      const providerMessages = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Explain the impact of modifying file "${targetFile.path}".\n\n${impactContext.text}` },
      ];

      const response = await aiProvider.generateResponse(providerMessages, {
        temperature: config.ai.chat.temperature,
        maxTokens: config.ai.chat.maxTokens,
      });

      impactData.explanation = response.content;
    } catch (error) {
      logger.warn('AI impact explanation generation failed', {
        projectId: project.id,
        fileId: targetFile.id,
        message: error.message,
      });
      impactData.explanation = 'AI explanation is currently unavailable. The factual graph above contains all analyzer-verified relationship details.';
    }
  }

  logger.info('Impact analysis completed', {
    projectId: project.id,
    fileId: targetFile.id,
    path: targetFile.path,
    directDependents: usedBy.length,
    directDependencies: dependsOn.length,
    totalAffected: affectedFiles.length,
    explained: shouldExplain,
  });

  return impactData;
}

module.exports = { getFileImpact };
